version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - npm install
      - npm run build
  filters:
    branches:
      only: develop
  test:
    docker:
      - image: circleci/golang:1.8.1
    steps:
      - npm install
      - npm run build
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
