version: 2
jobs:
   build-job:
     docker:
       - image: circleci/ruby:latest
     steps:
       - run: npm install
       - run: npm run build
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job